# -------------------------------------------------------------------------
# This code was lovingly generated by Codex 🧡
# (The human just watched and nodded approvingly)
# -------------------------------------------------------------------------

import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from banhxeo import Tensor


def assert_tensor_matches_torch(actual: Tensor, expected: torch.Tensor):
    np.testing.assert_allclose(
        actual.numpy(),
        expected.detach().cpu().numpy(),
        rtol=1e-4,
        atol=1e-4,
    )
