# -------------------------------------------------------------------------
# This code was lovingly generated by Codex 🧡
# (The human just watched and nodded approvingly)
# -------------------------------------------------------------------------

import pytest
import torch

from banhxeo import Tensor
from banhxeo.core.view import View
from conftest import assert_tensor_matches_torch


# ---------- View Metadata ----------


def test_create_contiguous_view_strides():
    view = View.create((2, 3, 4))

    assert view.shape == (2, 3, 4)
    assert view.strides == (12, 4, 1)
    assert view.offset == 0
    assert view.is_contiguous()


def test_create_scalar_view_has_empty_strides():
    view = View.create(())

    assert view.shape == ()
    assert view.strides == ()
    assert not view.is_contiguous()


def test_slice_updates_shape_and_offset():
    view = View.create((5,)).slice(((2, 5),))

    assert view.shape == (3,)
    assert view.strides == (1,)
    assert view.offset == 2


def test_slice_preserves_existing_offset():
    view = View((10,), (1,), offset=4).slice(((2, 5),))

    assert view.shape == (3,)
    assert view.offset == 6


def test_reshape_preserves_contiguous_view_offset():
    view = View((4,), (1,), offset=2).reshape((2, 2))

    assert view.shape == (2, 2)
    assert view.strides == (2, 1)
    assert view.offset == 2


def test_permute_changes_shape_and_strides():
    view = View.create((2, 3, 4)).permute((2, 0, 1))

    assert view.shape == (4, 2, 3)
    assert view.strides == (1, 12, 4)


def test_permute_preserves_offset():
    view = View((2, 3), (3, 1), offset=2).permute((1, 0))

    assert view.shape == (3, 2)
    assert view.strides == (1, 3)
    assert view.offset == 2


@pytest.mark.parametrize("axes", [(-1, 0), (0, 0), (0, 1, 2)])
def test_permute_rejects_invalid_axes(axes):
    with pytest.raises(ValueError):
        View.create((2, 3)).permute(axes)


def test_broadcast_uses_zero_stride_for_expanded_dimension():
    view = View.create((3, 1)).broadcast_to((3, 4))

    assert view.shape == (3, 4)
    assert view.strides == (1, 0)


def test_broadcast_can_add_left_dimensions():
    view = View.create((3,)).broadcast_to((2, 3))

    assert view.shape == (2, 3)
    assert view.strides == (0, 1)


def test_broadcast_preserves_offset():
    view = View((3, 1), (1, 1), offset=2).broadcast_to((3, 4))

    assert view.offset == 2


def test_broadcast_rejects_fewer_target_dimensions():
    assert not View.create((2, 3)).can_broadcast((3,))


def test_broadcast_rejects_incompatible_shape():
    assert not View.create((2, 3)).can_broadcast((2, 4))


# ---------- Tensor View Correctness ----------


def test_transpose_matches_torch_on_cpu():
    data = torch.arange(6, dtype=torch.float32).reshape(2, 3)

    assert_tensor_matches_torch(Tensor(data.numpy(), device="cpu").T, data.T)


def test_permute_matches_torch_on_cpu():
    data = torch.arange(24, dtype=torch.float32).reshape(2, 3, 4)

    actual = Tensor(data.numpy(), device="cpu").permute((2, 0, 1))
    expected = data.permute(2, 0, 1)

    assert_tensor_matches_torch(actual, expected)


def test_expand_matches_torch_on_cpu():
    data = torch.tensor([[1.0], [2.0], [3.0]])

    assert_tensor_matches_torch(
        Tensor(data.numpy(), device="cpu").expand((3, 4)),
        data.expand(3, 4),
    )


def test_integer_index_matches_torch_on_cpu():
    data = torch.arange(12, dtype=torch.float32).reshape(3, 4)

    assert_tensor_matches_torch(Tensor(data.numpy(), device="cpu")[1], data[1])


def test_basic_slice_matches_torch_on_cpu():
    data = torch.arange(20, dtype=torch.float32).reshape(4, 5)

    assert_tensor_matches_torch(
        Tensor(data.numpy(), device="cpu")[1:4, 2:5],
        data[1:4, 2:5],
    )


def test_step_slice_matches_torch_on_cpu():
    data = torch.arange(20, dtype=torch.float32).reshape(4, 5)

    assert_tensor_matches_torch(
        Tensor(data.numpy(), device="cpu")[::2, 1:5:2],
        data[::2, 1:5:2],
    )


def test_chained_slice_matches_torch_on_cpu():
    data = torch.arange(20, dtype=torch.float32).reshape(4, 5)

    actual = Tensor(data.numpy(), device="cpu")[1:4][:, 1:4]
    expected = data[1:4][:, 1:4]

    assert_tensor_matches_torch(actual, expected)


def test_view_then_elementwise_matches_torch_on_cpu():
    data = torch.arange(6, dtype=torch.float32).reshape(2, 3)

    actual = Tensor(data.numpy(), device="cpu").T + 1.0
    expected = data.T + 1.0

    assert_tensor_matches_torch(actual, expected)


# ---------- Module 1 Future Work ----------


@pytest.mark.xfail(reason="View.to_index_expr is a Module 1 assignment")
def test_view_to_index_expr_exists_for_codegen_single_source_of_truth():
    View.create((2, 3)).to_index_expr("idx", "x")


@pytest.mark.xfail(reason="View.shrink is a Module 1 assignment")
def test_view_shrink_crops_with_offset_only():
    view = View.create((4, 4)).shrink(((1, 3), (1, 3)))

    assert view.shape == (2, 2)
    assert view.strides == (4, 1)
    assert view.offset == 5


@pytest.mark.xfail(reason="View.flip is a Module 1 assignment")
def test_view_flip_uses_negative_stride():
    view = View.create((4,)).flip(0)

    assert view.shape == (4,)
    assert view.strides == (-1,)
    assert view.offset == 3


@pytest.mark.xfail(reason="View.pad is a Module 1 assignment")
def test_view_pad_records_mask_or_equivalent_valid_region():
    View.create((3,)).pad(((2, 1),))
