# https://github.com/astral-sh/trusted-publishing-examples/blob/main/.github/workflows/ci.yml
# Basic CI setup: Lint with ruff, run tests with pytest
name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Ruff lint
        run: uv run ruff check src/banhxeo/
      - name: Ruff format
        run: uv run ruff format --diff .

  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Update pytest
        run: uv sync --extra tests
      - run: uv run pytest tests